- name: user
  hosts: user
  become: yes
  tasks:
  - name: disable old nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add user
    ansible.builtin.user:
      name: roboshop
  - name: remove directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
  - name: unzip app
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  - name: download dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: setup user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: install mongodb client
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  - name: get the users count
    ansible.builtin.shell:  mongo --host mongodb.littlesimba.online --quiet --eval 'db = db. getSiblingDB("users"); db.users.count()'
    register: user_count
  - name: load schema
    ansible.builtin.command: mongo --host mongodb.littlesimba.online </app/schema/user.js
    when: user_count.stdout == "0"
  - name: enable and start user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes